# Generated by Django 2.2.4 on 2019-08-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
