# Generated by Django 2.2.4 on 2019-10-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_siteuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
