# Generated by Django 2.2.4 on 2019-08-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_post_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
