# Generated by Django 2.2.4 on 2019-08-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190819_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='seen',
        ),
    ]
