# Generated by Django 2.2.4 on 2019-08-20 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_postinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 15, 37, 56, 408694), verbose_name='release date'),
            preserve_default=False,
        ),
    ]
