# Generated by Django 2.2.4 on 2019-08-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_post_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
