# Generated by Django 2.2.4 on 2019-08-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20190820_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostInteraction',
        ),
    ]
