# Generated by Django 2.2.4 on 2019-09-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_link',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
